# Generated by Django 3.2.7 on 2021-10-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.BigIntegerField()),
                ('mount_point', models.CharField(max_length=300)),
                ('mount_state', models.CharField(choices=[('mount', 'mount'), ('unmount', 'unmount')], max_length=7)),
                ('format', models.BooleanField(default=False)),
            ],
        ),
    ]
