# Generated by Django 3.2.7 on 2021-10-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='mount_state',
            field=models.CharField(choices=[('mount', 'mount'), ('umount', 'umount')], max_length=7),
        ),
    ]
