# Generated by Django 3.2.7 on 2021-10-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_disk_mount_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='mount_point',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='disk',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='disk',
            name='size',
            field=models.IntegerField(verbose_name='Disk size in Gb'),
        ),
    ]
